# Created using wingetcreate 1.0.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: roryok.poe-writer
PackageVersion: 2.3.16
PackageLocale: en-US
Publisher: Rory O'Kelly
PublisherUrl: https://getpoe.com/
Author: Rory O'Kelly
PackageName: Poe Writer
PackageUrl: https://github.com/roryok/poe-auto-updater/releases/tag/v2.3.16
License: Proprietary
ShortDescription: POE is a distraction free writing app built by writers for writers. It has a minimalist, focused editor with lots of powerful features just a click away, but out of sight until you need them.
Description: POE is a distraction free writing app built by writers for writers. It has a minimalist, focussed editor with lots of powerful features just a click away, out of sight.
Moniker: POE
ManifestType: defaultLocale
ManifestVersion: 1.1.0

